name: docs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install mkdocs-material 
          pip install mkdocs-gen-files 
          pip install mkdocs-literate-nav 
          pip install mkdocs-section-index 
          pip install mkdocstrings 
          pip install mkdocstrings-python 
          pip install mkdocs-jupyter 
          pip install mkdocs-autorefs
          pip install -e .
      - name: Build and deploy docs
        run: mkdocs gh-deploy --force
        if: github.ref == 'refs/heads/main'